apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring4shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring4shell
  template:
    metadata:
      labels:
        app: spring4shell
    spec:
      containers:
      - name: spring4shell
        image: berrakkafa/spring4shell:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

